name: Release Maven

on:
  workflow_dispatch:
    inputs:
      releaseVersion:
        description: "Version to use when preparing a release (e.g., 0.1.0)"
        required: true
        default: "0.3.2"
      developmentVersion:
        description: "Next development version (e.g., 0.1.1-SNAPSHOT)"
        required: true
        default: "0.3.2-SNAPSHOT"

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false

jobs:
  release-maven:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    env:
      TZ: Europe/Berlin
      MAVEN_OPTS: "-Dhttp.socket.timeout=1800000 -Dhttp.connection.timeout=1800000"
    outputs:
      MVN_ARTIFACT_ID: ${{ steps.maven-release-step.outputs.MVN_ARTIFACT_ID }}
      ARTIFACT_NAME: ${{ steps.maven-release-step.outputs.artifact-name }}
    steps:
      - id: maven-release-step
        uses: it-at-m/lhm_actions/action-templates/actions/action-maven-release@7cb754b2056cebda6c36db344434f85be398c493 # v1.0.25
        with:
          app-path: "" # empty string so the action targets the root pom.xml without creating an invalid ././pom.xml path
          releaseVersion: ${{ inputs.releaseVersion }}
          developmentVersion: ${{ inputs.developmentVersion }}
          skipDeployment: "false"
          use-pr: "true"
          SIGN_KEY_PASS: ${{ secrets.gpg_passphrase }}
          CENTRAL_USERNAME: ${{ secrets.sonatype_username }}
          CENTRAL_PASSWORD: ${{ secrets.sonatype_password }}
          GPG_PRIVATE_KEY: ${{ secrets.gpg_private_key }}

  create-github-release:
    needs: release-maven
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: it-at-m/lhm_actions/action-templates/actions/action-create-github-release@7cb754b2056cebda6c36db344434f85be398c493 # v1.0.25
        with:
          artifact-name: ${{ needs.release-maven.outputs.ARTIFACT_NAME }}
          tag-name: v${{ inputs.releaseVersion }}
          artifact-path: |
            core/target/*.jar
            rest/target/*.jar
            web/target/*.jar
